# Generated by DevSwitch. Do not edit.
DEVSWITCH_NODE_HOME="/opt/node-v22.11.0"
DEVSWITCH_JAVA_HOME="/usr/lib/jvm/jdk-17.0.9"
DEVSWITCH_MAVEN_HOME=""
DEVSWITCH_GRADLE_HOME=""
_devswitch_front() {
  target="$1"
  [ -n "$target" ] || return 0
  new=""
  oldifs="$IFS"
  IFS=:
  for p in $PATH; do
    [ "$p" = "$target" ] && continue
    if [ -z "$new" ]; then new="$p"; else new="$new:$p"; fi
  done
  IFS="$oldifs"
  PATH="$target${new:+:$new}"
}
if [ -n "$DEVSWITCH_JAVA_HOME" ]; then
  export JAVA_HOME="$DEVSWITCH_JAVA_HOME"
  _devswitch_front "$JAVA_HOME/jre/bin"
  _devswitch_front "$JAVA_HOME/bin"
fi
if [ -n "$DEVSWITCH_MAVEN_HOME" ]; then
  export MAVEN_HOME="$DEVSWITCH_MAVEN_HOME"
  _devswitch_front "${MAVEN_HOME}/bin"
fi
if [ -n "$DEVSWITCH_GRADLE_HOME" ]; then
  export GRADLE_HOME="$DEVSWITCH_GRADLE_HOME"
  _devswitch_front "${GRADLE_HOME}/bin"
fi
if [ -n "$DEVSWITCH_NODE_HOME" ]; then
  _devswitch_front "$DEVSWITCH_NODE_HOME/bin"
fi
_devswitch_front "/home/tester/.local/bin"
export PATH
unset -f _devswitch_front
