// Package apply 负责一切「生效动作」：shim / env / 钩子。
// Linux 侧生成物与 Python 版 golden 基线逐字节一致（见 apply_test.go）。
package apply

import (
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/xyztony999/devswitch/internal/models"
	"github.com/xyztony999/devswitch/internal/paths"
)

// Windows 上构建工具的真实入口。
var WinNodeTargets = map[string]string{
	"node": "node.exe", "npm": "npm.cmd", "npx": "npx.cmd", "corepack": "corepack.cmd",
}
var WinBuildtoolTargets = map[string]string{
	"mvn": "mvn.cmd", "mvnDebug": "mvnDebug.cmd", "gradle": "gradle.bat",
}

var shimMissingByKind = map[string]string{
	"node":      "DevSwitch: 未配置 Node，或当前版本没有 {n}。运行 devswitch list / use",
	"java":      "DevSwitch: 未配置 Java，或当前 JDK 没有 {n}。运行 devswitch list / use",
	"maven":     "DevSwitch: 未配置 Maven，或当前版本没有 {n}。运行 devswitch list / use",
	"gradle":    "DevSwitch: 未配置 Gradle，或当前版本没有 {n}。运行 devswitch list / use",
	"node-tool": "DevSwitch: 当前 Node 没有 {n}。用这套 Node 执行 npm i -g 安装，或切到装过它的版本。",
}

func missingMessage(kind, name string) string {
	return strings.ReplaceAll(shimMissingByKind[kind], "{n}", name)
}

// quote 手动拼双引号：Go 的 %q 会把 Windows 路径反斜杠转义成 \\，
// 而 Python 生成物是字面反斜杠，golden 字节对齐必须用它。
func quote(s string) string { return `"` + s + `"` }

func writeFile(path, text string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(text), 0o644) // 精确字节，不做换行转换
}

func writeExecutable(path, text string) error {
	if err := writeFile(path, text); err != nil {
		return err
	}
	return os.Chmod(path, 0o755)
}

func envHome(state *models.State, tool models.Tool) string {
	if runtime := state.CurrentRuntime(tool); runtime != nil {
		return runtime.Home
	}
	return ""
}

// WriteCurrentEnv 写 current.env（仅 Linux；Windows shim 内嵌路径）。
func WriteCurrentEnv(state *models.State) error {
	if paths.IsWindows {
		return nil
	}
	lines := []string{"# Generated by DevSwitch. Do not edit."}
	for _, tool := range models.Tools {
		home := strings.TrimRight(envHome(state, tool), "/")
		lines = append(lines,
			"DEVSWITCH_"+strings.ToUpper(string(tool))+"_HOME="+quote(home))
	}
	lines = append(lines, "")
	return writeFile(paths.CurrentEnv(), strings.Join(lines, "\n"))
}

var frontFunction = []string{
	"_devswitch_front() {",
	`  target="$1"`,
	`  [ -n "$target" ] || return 0`,
	`  new=""`,
	`  oldifs="$IFS"`,
	"  IFS=:",
	`  for p in $PATH; do`,
	`    [ "$p" = "$target" ] && continue`,
	`    if [ -z "$new" ]; then new="$p"; else new="$new:$p"; fi`,
	"  done",
	`  IFS="$oldifs"`,
	`  PATH="$target${new:+:$new}"`,
	"}",
}

// WriteEnvSh 写 shell 钩子引用的 env.sh。所有工具块无条件生成
// （变量为空时 if 分支自然不生效），与 Python 版/golden 一致。
func WriteEnvSh(state *models.State) error {
	if paths.IsWindows {
		return writeEnvShGdBash(state)
	}
	posix := filepath.ToSlash
	lines := []string{"# Generated by DevSwitch. Do not edit."}
	for _, tool := range models.Tools {
		home := ""
		if h := envHome(state, tool); h != "" {
			home = posix(h)
		}
		lines = append(lines,
			"DEVSWITCH_"+strings.ToUpper(string(tool))+"_HOME="+quote(home))
	}
	lines = append(lines, frontFunction...)
	lines = append(lines,
		`if [ -n "$DEVSWITCH_JAVA_HOME" ]; then`,
		`  export JAVA_HOME="$DEVSWITCH_JAVA_HOME"`,
		`  _devswitch_front "$JAVA_HOME/jre/bin"`,
		`  _devswitch_front "$JAVA_HOME/bin"`,
		"fi",
	)
	for _, tool := range []models.Tool{models.Maven, models.Gradle} {
		upper := strings.ToUpper(string(tool))
		varName := models.ToolHomeVars[tool]
		lines = append(lines,
			`if [ -n "$DEVSWITCH_`+upper+`_HOME" ]; then`,
			`  export `+varName+`="$DEVSWITCH_`+upper+`_HOME"`,
			`  _devswitch_front "${`+varName+`}/bin"`,
			"fi",
		)
	}
	lines = append(lines,
		`if [ -n "$DEVSWITCH_NODE_HOME" ]; then`,
		`  _devswitch_front "$DEVSWITCH_NODE_HOME/bin"`,
		"fi",
		"_devswitch_front "+quote(posix(paths.LocalBin())),
		"export PATH",
		"unset -f _devswitch_front",
		"",
	)
	return writeFile(paths.EnvFile(), strings.Join(lines, "\n"))
}

// writeEnvShGdBash 生成 Git Bash 版 env.sh：PATH 项用 MSYS 形式，
// JAVA_HOME 保持 Windows 形式供 mvn.cmd 等使用。
func writeEnvShGdBash(state *models.State) error {
	javaWin := ""
	lines := []string{"# Generated by DevSwitch. Do not edit."}
	for _, tool := range models.Tools {
		msys := ""
		if h := envHome(state, tool); h != "" {
			win := WinHome(h)
			msys = ToMsysPath(win)
			if tool == models.Java {
				javaWin = win
			}
		}
		lines = append(lines,
			"DEVSWITCH_"+strings.ToUpper(string(tool))+"_HOME="+quote(msys))
	}
	if javaWin != "" {
		lines = append(lines, "DEVSWITCH_JAVA_HOME_WIN="+quote(javaWin))
	}
	lines = append(lines, frontFunction...)
	lines = append(lines,
		`if [ -n "$DEVSWITCH_JAVA_HOME" ]; then`,
		`  export JAVA_HOME="${DEVSWITCH_JAVA_HOME_WIN:-$DEVSWITCH_JAVA_HOME}"`,
		`  _devswitch_front "$DEVSWITCH_JAVA_HOME/jre/bin"`,
		`  _devswitch_front "$DEVSWITCH_JAVA_HOME/bin"`,
		"fi",
	)
	for _, tool := range []models.Tool{models.Maven, models.Gradle} {
		upper := strings.ToUpper(string(tool))
		varName := models.ToolHomeVars[tool]
		lines = append(lines,
			`if [ -n "$DEVSWITCH_`+upper+`_HOME" ]; then`,
			`  export `+varName+`="$DEVSWITCH_`+upper+`_HOME"`,
			`  _devswitch_front "${`+varName+`}/bin"`,
			"fi",
		)
	}
	lines = append(lines,
		`if [ -n "$DEVSWITCH_NODE_HOME" ]; then`,
		`  _devswitch_front "$DEVSWITCH_NODE_HOME"`,
		"fi",
		"_devswitch_front "+quote(ToMsysPath(paths.LocalBin())),
		"export PATH",
		"unset -f _devswitch_front",
		"",
	)
	return writeFile(paths.EnvFile(), strings.Join(lines, "\n"))
}

// WinHome 规范化 Windows 风格 home（反斜杠、去尾分隔符）。
func WinHome(home string) string {
	return strings.ReplaceAll(strings.TrimRight(home, "/\\"), "/", "\\")
}

// ToMsysPath 把 C:\x\y 转为 /c/x/y（UNC → //srv/share）。
func ToMsysPath(path string) string {
	path = filepath.ToSlash(path)
	if strings.HasPrefix(path, "//") {
		return path
	}
	if len(path) >= 2 && path[1] == ':' {
		return "/" + strings.ToLower(path[:1]) + path[2:]
	}
	return path
}

// HookSnippet 生成 .bashrc/.profile 用的 sh 钩子块。
func HookSnippet() string {
	env := filepath.ToSlash(paths.EnvFile())
	if paths.IsWindows {
		env = ToMsysPath(env)
	}
	return strings.Join([]string{
		paths.HookBegin,
		"if [ -f "+quote(env)+" ]; then",
		"  . "+quote(env),
		"fi",
		paths.HookEnd,
		"",
	}, "\n")
}

var hookFullRe = regexp.MustCompile(regexp.QuoteMeta(paths.HookBegin) + `(?s).*?` + regexp.QuoteMeta(paths.HookEnd))

// InstallHook 写入/更新目标文件中的钩子块，返回是否新增。
func InstallHook(path string) (bool, error) {
	snippet := strings.TrimRight(HookSnippet(), "\n")
	text := ""
	if data, err := os.ReadFile(path); err == nil {
		text = string(data)
	}
	if strings.Contains(text, paths.HookBegin) && strings.Contains(text, paths.HookEnd) {
		updated := hookFullRe.ReplaceAllString(text, snippet)
		if !strings.HasSuffix(updated, "\n") {
			updated += "\n"
		}
		return false, writeFile(path, updated)
	}
	if text != "" && !strings.HasSuffix(text, "\n") {
		text += "\n"
	}
	return true, writeFile(path, text+"\n"+snippet+"\n")
}

var hookRemoveRe = regexp.MustCompile(`\n?` + regexp.QuoteMeta(paths.HookBegin) + `(?s).*?` + regexp.QuoteMeta(paths.HookEnd) + `\n?`)

// RemoveHook 从目标文件删除钩子块。
func RemoveHook(path string) bool {
	data, err := os.ReadFile(path)
	if err != nil || !strings.Contains(string(data), paths.HookBegin) {
		return false
	}
	updated := hookRemoveRe.ReplaceAllString(string(data), "")
	if !strings.HasSuffix(updated, "\n") {
		updated += "\n"
	}
	return writeFile(path, updated) == nil
}

// HookInstalled 判断文件中是否已有钩子块。
func HookInstalled(path string) bool {
	data, err := os.ReadFile(path)
	if err != nil {
		return false
	}
	text := string(data)
	return strings.Contains(text, paths.HookBegin) && strings.Contains(text, paths.HookEnd)
}

// IsOurShim 判断文件是否是我们生成的 shim（含标记且非符号链接）。
func IsOurShim(path string) bool {
	info, err := os.Lstat(path)
	if err != nil || info.Mode()&os.ModeSymlink != 0 {
		return false
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return false
	}
	return strings.Contains(string(data), paths.ShimMarker)
}
