# -*- coding: utf-8 -*-
from __future__ import print_function, unicode_literals

import os
import re
import shutil
import stat
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional, Tuple

from . import paths
from .models import JAVA_SHIMS, NODE_SHIMS, Runtime, State
from .store import save_state

RESERVED_SHIMS = set(NODE_SHIMS + JAVA_SHIMS + ("devswitch", "devswitch-gui"))


NODE_PATH_RE = re.compile(
    r"^(\s*export\s+PATH=.*(?:node-v|/n/versions/node|\.nvm/versions/node).*)",
    re.I,
)


def _posix(path):
    return str(Path(path))


def _write_text(path, text, newline):
    # type: (Path, str, str) -> None
    # `text` already carries the exact EOLs for its platform (sh: \n, cmd:
    # \r\n); newline="" disables translation so bytes are host-independent.
    # Path.open passes through io.open: the newline kwarg works on every
    # supported Python (3.8+), unlike Path.write_text(newline=...) (3.10+).
    with path.open("w", encoding="utf-8", newline="") as handle:
        handle.write(text)


def _win_home(home):
    # type: (str) -> str
    return str(home).rstrip("\\/").replace("/", "\\")


def extra_node_bins(state):
    # type: (State) -> Dict[str, List[str]]
    # Only the active Node: globals follow the version you switched to.
    # On Windows npm globals live in the shared %APPDATA%\npm instead.
    if paths.IS_WINDOWS:
        return {}
    found = {}  # type: Dict[str, List[str]]
    current = state.current_runtime("node") if state else None
    if current is None:
        return found
    home = current.home.rstrip("/")
    if home in ("/usr", "/usr/local", "/"):
        return found
    bindir = Path(home) / "bin"
    if not bindir.is_dir():
        return found
    for entry in bindir.iterdir():
        name = entry.name
        if name in RESERVED_SHIMS:
            continue
        try:
            if not entry.is_file() or not os.access(str(entry), os.X_OK):
                continue
        except OSError:
            continue
        found.setdefault(name, []).append(home)
    return found


def write_current_env(state):
    # type: (State) -> None
    if paths.IS_WINDOWS:
        return  # Windows shims embed the current paths instead.
    node = state.current_runtime("node")
    java = state.current_runtime("java")
    current = node.home.rstrip("/") if node else ""
    lines = [
        "# Generated by DevSwitch. Do not edit.",
        'DEVSWITCH_NODE_HOME="{}"'.format(current),
        'DEVSWITCH_JAVA_HOME="{}"'.format(_posix(java.home) if java else ""),
        "",
    ]
    _write_text(paths.current_env_file(), "\n".join(lines), "\n")


def write_env_sh(state):
    # type: (State) -> None
    node = state.current_runtime("node")
    java = state.current_runtime("java")
    if paths.IS_WINDOWS:
        write_env_sh_gdbash(state, node, java)
        return
    local_bin = _posix(paths.local_bin())
    node_home = _posix(node.home) if node else ""
    java_home = _posix(java.home) if java else ""
    lines = [
        "# Generated by DevSwitch. Do not edit.",
        'DEVSWITCH_NODE_HOME="{}"'.format(node_home),
        'DEVSWITCH_JAVA_HOME="{}"'.format(java_home),
        "_devswitch_front() {",
        '  target="$1"',
        '  [ -n "$target" ] || return 0',
        '  new=""',
        '  oldifs="$IFS"',
        "  IFS=:",
        '  for p in $PATH; do',
        '    [ "$p" = "$target" ] && continue',
        '    if [ -z "$new" ]; then new="$p"; else new="$new:$p"; fi',
        "  done",
        '  IFS="$oldifs"',
        '  PATH="$target${new:+:$new}"',
        "}",
        'if [ -n "$DEVSWITCH_JAVA_HOME" ]; then',
        '  export JAVA_HOME="$DEVSWITCH_JAVA_HOME"',
        '  _devswitch_front "$JAVA_HOME/jre/bin"',
        '  _devswitch_front "$JAVA_HOME/bin"',
        "fi",
        'if [ -n "$DEVSWITCH_NODE_HOME" ]; then',
        '  _devswitch_front "$DEVSWITCH_NODE_HOME/bin"',
        "fi",
        '_devswitch_front "{}"'.format(local_bin),
        "export PATH",
        "unset -f _devswitch_front",
        "",
    ]
    _write_text(paths.env_file(), "\n".join(lines), "\n")


def write_env_sh_gdbash(state, node, java):
    # type: (State, Optional[Runtime], Optional[Runtime]) -> None
    # Git Bash variant: PATH entries in MSYS form (a "C:\..." entry would
    # break the colon-separated PATH), JAVA_HOME stays in Windows form for
    # cmd-based tools like mvn.cmd.
    from . import winenv

    local_bin = winenv.to_msys_path(str(paths.local_bin()))
    node_home = winenv.to_msys_path(_win_home(node.home)) if node else ""
    java_win = _win_home(java.home) if java else ""
    java_msys = winenv.to_msys_path(java_win) if java else ""
    lines = [
        "# Generated by DevSwitch. Do not edit.",
        'DEVSWITCH_NODE_HOME="{}"'.format(node_home),
        'DEVSWITCH_JAVA_HOME_WIN="{}"'.format(java_win),
        'DEVSWITCH_JAVA_HOME_MSYS="{}"'.format(java_msys),
        "_devswitch_front() {",
        '  target="$1"',
        '  [ -n "$target" ] || return 0',
        '  new=""',
        '  oldifs="$IFS"',
        "  IFS=:",
        '  for p in $PATH; do',
        '    [ "$p" = "$target" ] && continue',
        '    if [ -z "$new" ]; then new="$p"; else new="$new:$p"; fi',
        "  done",
        '  IFS="$oldifs"',
        '  PATH="$target${new:+:$new}"',
        "}",
        'if [ -n "$DEVSWITCH_JAVA_HOME_MSYS" ]; then',
        '  export JAVA_HOME="$DEVSWITCH_JAVA_HOME_WIN"',
        '  _devswitch_front "$DEVSWITCH_JAVA_HOME_MSYS/jre/bin"',
        '  _devswitch_front "$DEVSWITCH_JAVA_HOME_MSYS/bin"',
        "fi",
        'if [ -n "$DEVSWITCH_NODE_HOME" ]; then',
        '  _devswitch_front "$DEVSWITCH_NODE_HOME"',
        "fi",
        '_devswitch_front "{}"'.format(local_bin),
        "export PATH",
        "unset -f _devswitch_front",
        "",
    ]
    _write_text(paths.env_file(), "\n".join(lines), "\n")


def write_user_env(state):
    # type: (State) -> None
    # Windows persistence: user PATH entry + JAVA_HOME in HKCU\Environment.
    if not paths.IS_WINDOWS:
        return
    from . import winenv

    winenv.ensure_path_entry(str(paths.local_bin()), first=True)
    java = state.current_runtime("java")
    if java is not None:
        winenv.set_user_java_home(_win_home(java.home))


def _shim_script(tool_kind, name, state=None):
    # type: (str, str, Optional[State]) -> str
    if paths.IS_WINDOWS:
        return _shim_script_windows(tool_kind, name, state)
    env_path = _posix(paths.current_env_file())
    if tool_kind == "node":
        lookup = (
            'if [ -n "$DEVSWITCH_NODE_HOME" ] && [ -x "$DEVSWITCH_NODE_HOME/bin/{name}" ]; then\n'
            '  exec "$DEVSWITCH_NODE_HOME/bin/{name}" "$@"\n'
            "fi\n"
        ).format(name=name)
        missing = "DevSwitch: 未配置 Node，或当前版本没有 {}。运行 devswitch list / use".format(name)
    elif tool_kind == "node-tool":
        return (
            "#!/bin/sh\n"
            "# DevSwitch shim — {name}\n"
            'ENVFILE="{env}"\n'
            '[ -f "$ENVFILE" ] && . "$ENVFILE"\n'
            'if [ -n "$DEVSWITCH_NODE_HOME" ] && [ -x "$DEVSWITCH_NODE_HOME/bin/{name}" ]; then\n'
            '  PATH="$DEVSWITCH_NODE_HOME/bin:$PATH"\n'
            '  exec "$DEVSWITCH_NODE_HOME/bin/{name}" "$@"\n'
            "fi\n"
            'echo "DevSwitch: 当前 Node 没有 {name}。用这套 Node 执行 npm i -g 安装，或切到装过它的版本。" >&2\n'
            "exit 127\n"
        ).format(name=name, env=env_path)
    else:
        lookup = (
            'if [ -n "$DEVSWITCH_JAVA_HOME" ]; then\n'
            '  if [ -x "$DEVSWITCH_JAVA_HOME/bin/{name}" ]; then\n'
            '    exec "$DEVSWITCH_JAVA_HOME/bin/{name}" "$@"\n'
            '  elif [ -x "$DEVSWITCH_JAVA_HOME/jre/bin/{name}" ]; then\n'
            '    exec "$DEVSWITCH_JAVA_HOME/jre/bin/{name}" "$@"\n'
            "  fi\n"
            "fi\n"
        ).format(name=name)
        missing = "DevSwitch: 未配置 Java，或当前 JDK 没有 {}。运行 devswitch list / use".format(name)
    return (
        "#!/bin/sh\n"
        "# DevSwitch shim — {name}\n"
        'ENVFILE="{env}"\n'
        '[ -f "$ENVFILE" ] && . "$ENVFILE"\n'
        "{lookup}"
        'echo "{missing}" >&2\n'
        "exit 127\n"
    ).format(name=name, env=env_path, lookup=lookup, missing=missing)


WIN_NODE_TARGETS = {
    "node": "node.exe",
    "npm": "npm.cmd",
    "npx": "npx.cmd",
    "corepack": "corepack.cmd",
}


def _win_missing_lines(name):
    # type: (str) -> List[str]
    return [
        'echo DevSwitch: 未配置所选版本，或当前版本没有 {n}。运行 devswitch list / use 1>&2'.format(
            n=name
        ),
        "exit /b 127",
    ]


def _win_shim_targets(kind, name, state):
    # type: (str, str, Optional[State]) -> List[str]
    if kind == "node":
        runtime = state.current_runtime("node") if state else None
        if runtime is None:
            return []
        home = _win_home(runtime.home)
        return [home + "\\" + WIN_NODE_TARGETS[name]]
    runtime = state.current_runtime("java") if state else None
    if runtime is None:
        return []
    home = _win_home(runtime.home)
    return [home + "\\bin\\" + name + ".exe", home + "\\jre\\bin\\" + name + ".exe"]


def _shim_script_windows(kind, name, state):
    # type: (str, str, Optional[State]) -> str
    targets = _win_shim_targets(kind, name, state)
    missing = (
        "DevSwitch: 未配置 Node，或当前版本没有 {n}。运行 devswitch list / use".format(n=name)
        if kind == "node"
        else "DevSwitch: 未配置 Java，或当前 JDK 没有 {n}。运行 devswitch list / use".format(n=name)
    )
    lines = [
        "@echo off",
        "rem DevSwitch shim — {}".format(name),
    ]
    if not targets:
        lines.append("rem (no runtime selected)")
        lines.extend(_win_missing_lines(name))
        lines.append("")
        return "\r\n".join(lines)
    for index, target in enumerate(targets):
        label = "run" if index == 0 else "run{}".format(index)
        lines.append('if exist "{}" goto {}'.format(target, label))
    lines.append("echo {} 1>&2".format(missing))
    lines.append("exit /b 127")
    for index, target in enumerate(targets):
        label = "run" if index == 0 else "run{}".format(index)
        lines.append(":{}".format(label))
        lines.append('"{}" %*'.format(target))
    lines.append("")
    return "\r\n".join(lines)


def _shim_script_windows_sh(kind, name, state):
    # type: (str, str, Optional[State]) -> str
    # Extension-less sh twin of the .cmd shim: Git Bash resolves `name` before
    # `name.cmd`, so without it bash would skip us and hit the real runtime.
    from . import winenv

    targets = [
        winenv.to_msys_path(target) for target in _win_shim_targets(kind, name, state)
    ]
    if kind == "node":
        missing = "DevSwitch: 未配置 Node，或当前版本没有 {n}。运行 devswitch list / use".format(n=name)
    else:
        missing = "DevSwitch: 未配置 Java，或当前 JDK 没有 {n}。运行 devswitch list / use".format(n=name)
    lines = [
        "#!/bin/sh",
        "# DevSwitch shim — {}".format(name),
    ]
    for target in targets:
        # MSYS bash reports .cmd/.bat as non-executable; -f still gates them
        # and exec works by delegating to cmd.exe.
        if target.lower().endswith((".cmd", ".bat")):
            lines.append('if [ -f "{}" ]; then'.format(target))
        else:
            lines.append('if [ -x "{}" ]; then'.format(target))
        lines.append('  exec "{}" "$@"'.format(target))
        lines.append("fi")
    lines.append('echo "{}" >&2'.format(missing))
    lines.append("exit 127")
    lines.append("")
    return "\n".join(lines)


def _is_our_shim(path):
    # type: (Path) -> bool
    try:
        if not path.exists() or path.is_symlink():
            return False
        return "DevSwitch shim" in path.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return False


def _backup(path):
    # type: (Path) -> Optional[Path]
    if not path.exists():
        return None
    stamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    dest = paths.backup_dir() / "{}{}".format(path.name, "." + stamp)
    if path.is_symlink() or path.is_file():
        shutil.copy2(str(path), str(dest), follow_symlinks=False)
        return dest
    return None


def _write_one_shim(kind, name, state=None):
    # type: (str, str, Optional[State]) -> List[str]
    bin_dir = paths.local_bin()
    written = []
    if paths.IS_WINDOWS:
        # cmd/PowerShell take the .cmd twin, Git Bash the sh twin.
        dests = [
            (bin_dir / (name + ".cmd"), _shim_script_windows(kind, name, state), "\r\n"),
            (bin_dir / name, _shim_script_windows_sh(kind, name, state), "\n"),
        ]
    else:
        dests = [
            (bin_dir / name, _shim_script(kind, name, state), "\n"),
        ]
    for dest, content, newline in dests:
        if dest.exists() and not _is_our_shim(dest) and name not in NODE_SHIMS + JAVA_SHIMS:
            continue
        if dest.exists() and not _is_our_shim(dest):
            _backup(dest)
            dest.unlink()
        _write_text(dest, content, newline)
        if not paths.IS_WINDOWS:
            dest.chmod(dest.stat().st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)
        written.append(str(dest))
    return written


def write_shims(state=None):
    # type: (Optional[State]) -> List[str]
    # Only take over a toolchain that is actually selected. Missing Node or Java
    # must not leave a stub in the shim dir that hides "command not found".
    written = []
    node_ok = state is not None and state.current_runtime("node") is not None
    java_ok = state is not None and state.current_runtime("java") is not None
    if node_ok:
        for name in NODE_SHIMS:
            written.extend(_write_one_shim("node", name, state))
    if java_ok:
        for name in JAVA_SHIMS:
            written.extend(_write_one_shim("java", name, state))
    extras = extra_node_bins(state) if node_ok else {}
    for name in extras:
        written.extend(_write_one_shim("node-tool", name, state))
    wanted = set(extras)
    if node_ok:
        wanted.update(NODE_SHIMS)
    if java_ok:
        wanted.update(JAVA_SHIMS)
    if paths.IS_WINDOWS:
        keep = set()
        for name in wanted:
            keep.add(name)
            keep.add(name + ".cmd")
        keep.update(("devswitch", "devswitch.cmd", "devswitch-gui", "devswitch-gui.cmd"))
    else:
        keep = set(wanted)
        keep.update(("devswitch", "devswitch-gui"))
    local_bin = paths.local_bin()
    if local_bin.is_dir():
        for dest in local_bin.iterdir():
            if dest.name in keep:
                continue
            if _is_our_shim(dest):
                dest.unlink()
    return written


def hook_snippet():
    env = _posix(paths.env_file())
    if paths.IS_WINDOWS:
        from . import winenv

        env = winenv.to_msys_path(env)  # Git Bash must source a POSIX-style path
    return (
        "{begin}\n"
        'if [ -f "{env}" ]; then\n'
        '  . "{env}"\n'
        "fi\n"
        "{end}\n"
    ).format(begin=paths.HOOK_BEGIN, env=env, end=paths.HOOK_END)


def hook_snippet_ps1():
    # type: () -> str
    # New terminals already inherit user env vars (JAVA_HOME, PATH) from the
    # registry; the session hook only has to put the shim dir ahead of the
    # machine PATH, which always sorts before the user PATH on Windows.
    bin_dir = str(paths.local_bin())
    return (
        "{begin}\n"
        "$_ds_bin = '{bin}'\n"
        "if (-not $env:Path.StartsWith($_ds_bin)) {{ $env:Path = \"$_ds_bin;$env:Path\" }}\n"
        "{end}\n"
    ).format(begin=paths.HOOK_BEGIN, bin=bin_dir, end=paths.HOOK_END)


def _snippet_for(path):
    # type: (Path) -> str
    if path.suffix == ".ps1":
        return hook_snippet_ps1().strip()
    return hook_snippet().strip()


def hook_installed(path):
    # type: (Path) -> bool
    if not path.exists():
        return False
    text = path.read_text(encoding="utf-8", errors="ignore")
    return paths.HOOK_BEGIN in text and paths.HOOK_END in text


def install_hook(path):
    # type: (Path) -> bool
    snippet = _snippet_for(path)
    if path.exists():
        text = path.read_text(encoding="utf-8", errors="ignore")
        if paths.HOOK_BEGIN in text and paths.HOOK_END in text:
            pattern = re.compile(
                re.escape(paths.HOOK_BEGIN) + r".*?" + re.escape(paths.HOOK_END),
                re.S,
            )
            # Function replacement: the snippet may contain Windows paths whose
            # backslashes would otherwise be read as escape sequences.
            text = pattern.sub(lambda _match: snippet, text)
            _write_text(path, text if text.endswith("\n") else text + "\n", "\n")
            return False
        if not text.endswith("\n"):
            text += "\n"
        _write_text(path, text + "\n" + snippet, "\n")
        return True
    path.parent.mkdir(parents=True, exist_ok=True)
    _write_text(path, snippet + "\n", "\n")
    return True


def remove_hook(path):
    # type: (Path) -> bool
    if not path.exists():
        return False
    text = path.read_text(encoding="utf-8", errors="ignore")
    if paths.HOOK_BEGIN not in text:
        return False
    pattern = re.compile(
        r"\n?" + re.escape(paths.HOOK_BEGIN) + r".*?" + re.escape(paths.HOOK_END) + r"\n?",
        re.S,
    )
    text = pattern.sub("", text)
    _write_text(path, text if text.endswith("\n") else text + "\n", "\n")
    return True


def apply_hooks(state=None):
    # type: (Optional[State]) -> None
    for target in paths.hook_targets():
        install_hook(target)
    write_user_env(state)


def comment_conflicting_path_lines(path):
    # type: (Path) -> List[str]
    if not path.exists():
        return []
    original = path.read_text(encoding="utf-8", errors="ignore")
    changed = []
    out_lines = []
    for line in original.splitlines(True):
        raw = line.rstrip("\n")
        if NODE_PATH_RE.match(raw) and not raw.lstrip().startswith("#"):
            out_lines.append("# DevSwitch: 已改由 ~/.local/bin 的 shim 接管\n")
            out_lines.append("# " + raw + "\n")
            changed.append(raw.strip())
        else:
            out_lines.append(line if line.endswith("\n") else line + "\n")
    if changed:
        backup = paths.backup_dir() / (path.name + "." + datetime.now().strftime("%Y%m%d-%H%M%S"))
        backup.write_text(original, encoding="utf-8")
        path.write_text("".join(out_lines), encoding="utf-8")
    return changed


def apply_switch(state, tool, runtime):
    # type: (State, str, Runtime) -> None
    state.current[tool] = runtime.home
    save_state(state)
    write_current_env(state)
    write_env_sh(state)
    write_shims(state)
    write_user_env(state)


def apply_all(state):
    # type: (State) -> None
    write_current_env(state)
    write_env_sh(state)
    write_shims(state)
    apply_hooks(state)


def conflicting_bashrc_lines():
    # type: () -> List[Tuple[Path, str]]
    found = []
    for file_path in (paths.bashrc(), paths.profile()):
        if not file_path.exists():
            continue
        for line in file_path.read_text(encoding="utf-8", errors="ignore").splitlines():
            if NODE_PATH_RE.match(line) and not line.lstrip().startswith("#"):
                found.append((file_path, line.strip()))
    return found
